#!/usr/bin/env bash
# Update Nginx configuration to run as the nginx user and listen on port 8080
sudo sed -i "s/#user www-data;/user nginx;/" /etc/nginx/nginx.conf
sudo sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-available/default
sudo sed -i "s/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/g" /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo systemctl stop apache2
sudo systemctl disable apache2
sudo systemctl restart nginx
